using Content.Shared.GURPS.Targeting;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.GURPS.Targeting;

[GenerateTypedNameReferences]
public sealed partial class TargetingDoll : UIWidget
{
    public bool ModifyLayers = true;
    public readonly Dictionary<TargetBodyPart, TextureButton> BodyParts = new();
    private BaseButton? _activeButton;
    public TargetingDoll()
    {
        RobustXamlLoader.Load(this);
    }

    public void Setup()
    {
        BodyParts.Clear();

        BodyParts.Add(TargetBodyPart.LeftEye, LeftEyeSelection);
        BodyParts.Add(TargetBodyPart.RightEye, RightEyeSelection);
        BodyParts.Add(TargetBodyPart.Mouth, MouthSelection);
        BodyParts.Add(TargetBodyPart.Head, HeadSelection);
        BodyParts.Add(TargetBodyPart.Neck, NeckSelection);
        BodyParts.Add(TargetBodyPart.RightArm, RightArmSelection);
        BodyParts.Add(TargetBodyPart.Torso, TorsoSelection);
        BodyParts.Add(TargetBodyPart.LeftArm, LeftArmSelection);
        BodyParts.Add(TargetBodyPart.RightHand, RightHandSelection);
        BodyParts.Add(TargetBodyPart.Groin, GroinSelection);
        BodyParts.Add(TargetBodyPart.LeftHand, LeftHandSelection);
        BodyParts.Add(TargetBodyPart.LeftLeg, LeftLegSelection);
        BodyParts.Add(TargetBodyPart.RightLeg, RightLegSelection);
        BodyParts.Add(TargetBodyPart.RightFoot, RightFootSelection);
        BodyParts.Add(TargetBodyPart.LeftFoot, LeftFootSelection);

        foreach (var button in BodyParts.Values)
            foreach (var control in button.Children)
                control.Visible = false;
    }

    public void SetActive(BaseButton? button)
    {
        if (button == null || button == _activeButton)
            return;

        if (_activeButton != null)
            ToggleChildVisibility(_activeButton, false);
        ToggleChildVisibility(button, true);
        _activeButton = button;
    }

    public void ToggleChildVisibility(BaseButton? button, bool visible)
    {
        if (button == null)
            return;

        foreach (var child in button.Children)
            child.Visible = visible;

    }
}
