using Content.Client.Paper.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Targeting;

[GenerateTypedNameReferences]
public sealed partial class TargetingDoll : UIWidget
{
    public bool ModifyLayers = true;

    public TargetingDoll()
    {
        RobustXamlLoader.Load(this);
        BackGround.Texture = Theme.ResolveTextureOrNull("targeting_doll.png")?.Texture;
    }
}
