using System.Numerics;
using Content.Client.Paper.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Targeting;

[GenerateTypedNameReferences]
public sealed partial class TargetingDoll : UIWidget
{
    public bool ModifyLayers = true;

    public TargetingDoll()
    {
        RobustXamlLoader.Load(this);
    }

    public void Setup()
    {
        BackGround.Texture = Theme.ResolveTextureOrNull("targeting_doll")?.Texture;
        BackGround.MinSize = new Vector2(192, 64);
        BackGround.TextureScale = new Vector2(2, 2);
    }
}
